canonicalRequest: Allow "UNSIGNED-PAYLOAD"
disruptek/sigv4 pull request #4
Opened 2021-03-28 08:58 UTC by ThomasTJdev

In the `canonicalRequest()` the payload is always hashed. But when using `AWS S3 GetObject` we need to provide the payload as is: "UNSIGNED-PAYLOAD". Otherwise our signing does not match.

https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-query-string-auth.html
```
You don't include a payload hash in the Canonical Request, because when you create a presigned URL, you don't know the payload content because the URL is used to upload an arbitrary payload. Instead, you use a constant string UNSIGNED-PAYLOAD.
```

2021-03-28 18:11 UTC, disruptek requested changes
The concept of supporting unsigned payloads sounds great, but I don't like having to do a string comparison against a special value in order to determine whether to hash the payload.  Why not just add an `Identity` value to the `SigningAlgo` enum and have it simply return its input?  Does that make sense?

2021-03-29 04:20 UTC, ThomasTJdev commented
That do sounds better, something like below?

```nim
SigningAlgo* = enum
    SHA256 = "AWS4-HMAC-SHA256"
    SHA512 = "AWS4-HMAC-SHA512"
    UnsignedPayload = "UNSIGNED-PAYLOAD" # or just UNSIGNED as enum
```

```nim
proc hash*(payload: string; digest: SigningAlgo): string =
  ## hash an arbitrary string using the given algorithm
  case digest
  of SHA256: result = computeSHA256(payload).toLowerHex
  of SHA512: result = computeSHA512(payload).toLowerHex
  of UnsignedPayload: result = $UnsignedPayload
```

```nim
# Usage
request = canonicalRequest(HttpGet, url, query, headers, payload, digest=UnsignedPayload)
```

2021-03-29 14:42 UTC, disruptek commented
Yep, looks good to me!

2021-03-29 19:31 UTC, disruptek commented
Should it have a test?

2021-03-30 02:50 UTC, ThomasTJdev commented
> Should it have a test?

Coming up! I would also like to add an example in the README on how how to create a presigned S3 download link?

2021-03-30 14:51 UTC, merged

2021-03-30 14:52 UTC, disruptek commented
It's in 1.1.0; thank you!